---
version: 0.2
env:
  variables:
    LAMBDA_BUCKET_PREFIX: binxio-public
    LAMBDA_BUCKET_REGION: eu-central-1
    MAKE_TARGET: deploy
phases:
  install:
    runtime-versions:
      docker: 19
      python: 3.7
    commands:
      - curl -JLO https://github.com/docker/buildx/releases/download/v0.7.0/buildx-v0.7.0.linux-amd64
      - mkdir -p ~/.docker/cli-plugins
      - mv buildx-v0.7.0.linux-amd64 ~/.docker/cli-plugins/docker-buildx
      - chmod a+rx ~/.docker/cli-plugins/docker-buildx
      - echo '{"registry-mirrors": ["https://mirror.gcr.io"]}' > /etc/docker/daemon.json
      - pkill -1 dockerd

  build:
    commands:
      - make S3_BUCKET_PREFIX=${LAMBDA_BUCKET_PREFIX} AWS_REGION=${LAMBDA_BUCKET_REGION} ${MAKE_TARGET:-deploy}
